name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Networking
        uses: actions/checkout@v4
        with:
          repository: 'rockiesgrizzly/Networking'
          path: 'Networking'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Create Config.xcconfig 
        run: |
          echo "GOOGLE_GEN_AI_KEY = ${GOOGLE_GEN_AI_KEY}" >> Portfolio/Core/Config.xcconfig 
          echo "OPENAI_KEY = ${OPENAI_KEY}" >> Portfolio/Core/Config.xcconfig 

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies -project Portfolio.xcodeproj -verbose

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -project Portfolio.xcodeproj -list -json | tr -d "\n") 
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device='iPhone 16' 
          echo "Device: $device"
          echo "Platform: $platform"
          
          if [ $scheme = default ]; 
            then scheme=$(cat default); 
          fi
          echo "Scheme: $scheme"
          
          filetype_parameter="project" && file_to_build="Portfolio.xcodeproj"; 
          file_to_build=`echo $file_to_build | awk '{print $1}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
  test:
    name: Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Networking
        uses: actions/checkout@v4
        with:
          repository: 'rockiesgrizzly/Networking'
          path: 'Networking'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Create Config.xcconfig 
        run: |
          echo "GOOGLE_GEN_AI_KEY = ${GOOGLE_GEN_AI_KEY}" >> Portfolio/Core/Config.xcconfig 
          echo "OPENAI_KEY = ${OPENAI_KEY}" >> Portfolio/Core/Config.xcconfig 

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies -project Portfolio.xcodeproj -verbose

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -project Portfolio.xcodeproj -list -json | tr -d "\n") 
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Set Test Scheme
        run: |
          scheme_list=$(xcodebuild -project Portfolio.xcodeproj -list -json | tr -d "\n")
          test_scheme=$(echo $scheme_list | ruby -e "require 'json'; 
          targets = JSON.parse(STDIN.gets)['project']['targets']
          test_target = targets.find { |target| target.end_with?('Tests') } 
          puts test_target || targets[0]
          ")
          echo $test_scheme | cat >test_scheme
          echo Using test_scheme scheme: $test_scheme

      - name: Test
        env:
          scheme: ${{ 'test_scheme' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device='iPhone 16' 
          echo "Device: $device"
          echo "Platform: $platform"
          
          if [ $scheme = test_scheme ]; 
            then scheme=$(cat test_scheme); 
          fi
          echo "Scheme: $scheme"
          
          filetype_parameter="project" && file_to_build="Portfolio.xcodeproj";
          file_to_build=`echo $file_to_build | awk '{print $1}'`
          echo "xcodebuild test-without-building"
          xcodebuild test-without-building -verbose -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
